version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade awscli
  build:
    commands:
      - echo "Deploying site to S3..."
      - aws s3 cp . s3://cicd-demo-site/ --recursive
